name: serverbridge
version: 1.0.7
main: com.sovereigncraft.serverbridge.ServerBridge
api-version: 1.20
description: Relays Minecraft chat to a Matrix room
author: CappyTech

commands:
  chat:
    description: Matrix chat commands
    usage: |
      /chat register - Register your Matrix account
      /chat unregister <password> - Unregister your Matrix account
      /chat setavatar - Set your Matrix avatar to your Minecraft skin